### ISSUE TITLE
Modelo E/R

### ISSUE THREAD

**Issue by mayb-ai** [mayb-ai/Projeto-ES-II#10]

**Comment by MatheusZanetti** [comment]
https://github.com/mayb-ai/Projeto-ES-II/tree/main/ModeloConceitual

**Comment by MatheusZanetti** [comment]
fazendo o modelo E/R

**Comment by MatheusZanetti** [comment]
Atualização para review e alteração de pasta (deixar mais organizado)
[ModeloER](https://github.com/mayb-ai/Projeto-ES-II/blob/main/ModeloER/EntidadeRelacionamentoGameral.png)
