### ISSUE TITLE
Tarefa 04 - Jornada do Usuário

### ISSUE THREAD

**Issue by mayb-ai** [mayb-ai/Projeto-ES-II#5]
Instruções
Desenvolver as Jornadas dos Usuários da sua aplicação.

Veja a apresentação em anexo.

Como entregar:

Criar um documento online (office 365 ou google docs).

Colocar um link no README.md

Enviar o repositório do projeto (todos enviam).

**Comment by mayb-ai** [comment]
https://github.com/mayb-ai/Projeto-ES-II/tree/main/DOCS

**Comment by MatheusZanetti** [comment]
[Link direto]([jornada das personas](https://fatecspgov-my.sharepoint.com/:w:/r/personal/matheus_zanetti01_fatec_sp_gov_br/Documents/Arquivos%20de%20Chat%20do%20Microsoft%20Teams/Jornada%20Do%20Usu%C3%A1rio.docx?d=wb6ce99950d70413cb52b5bf7d8a9501a&csf=1&web=1&e=cT8d1L))
