### ISSUE TITLE
Tarefa 06 - Protótipo em Baixa Fidelidade

### ISSUE THREAD

**Issue by mayb-ai** [mayb-ai/Projeto-ES-II#6]
Instruções
Protótipo em baixa fidelidade.
Veja o link: 

https://medium.com/ladies-that-ux-br/prot%C3%B3tipos-baixa-m%C3%A9dia-ou-alta-fidelidade-71d897559135

Focar nas principais dores
Subir o protótipo no GitHub
Enviar o link do GitHub

**Comment by MatheusZanetti** [comment]
https://github.com/mayb-ai/Projeto-ES-II/blob/main/Prototipo%20BN/baixo%20n%C3%ADvel.pdf

**Comment by MatheusZanetti** [comment]
Recomendo fazer o download do arquivo PDF e aumentar o zoom com Ctrl.
